class Ventas {
  int id;
  int nFactura;
  String tipo;
  String fecha;
  String vence;
  int codCLiente;
  String nombreCliente;
  int idUsuario;
  bool anulado;
  bool facturaCancelado;
  int numApertura;
  int codMoneda;
  double tipoCambio;
  bool exonerar;
  String observaciones;
  int idVendedor;
  bool apertado;
  String hora;
  double subTotal;
  double totalDescuento;
  double totalImpuesto;
  double subTotalGravado;
  double subTotalExento;
  double total;
  int idBodega;
  String autorizacionFEL;
  String numeroFEL;
  String serieFEL;
  bool electronica;
  String emisionFEL;
  String qr;
  String totalLetras;
  int noAbonos;
  double montoAbonos;
  String contacto;
  String telContacto;
  String anuladoPor;
  String nombrePaciente;
  String nitFacturado;
  String nombreFacturado;
  String direccionFacturado;
  bool dpi;
  bool recibido;
  String noGuia;
  String notas;
  int idTranspote;
  int cantidadCuotas;

  Ventas(
      {required this.id,
      required this.nFactura,
      required this.tipo,
      required this.fecha,
      required this.vence,
      required this.codCLiente,
      required this.nombreCliente,
      required this.idUsuario,
      required this.anulado,
      required this.facturaCancelado,
      required this.numApertura,
      required this.codMoneda,
      required this.tipoCambio,
      required this.exonerar,
      required this.observaciones,
      required this.idVendedor,
      required this.apertado,
      required this.hora,
      required this.subTotal,
      required this.totalDescuento,
      required this.totalImpuesto,
      required this.subTotalGravado,
      required this.subTotalExento,
      required this.total,
      required this.idBodega,
      required this.autorizacionFEL,
      required this.numeroFEL,
      required this.serieFEL,
      required this.electronica,
      required this.emisionFEL,
      required this.qr,
      required this.totalLetras,
      required this.noAbonos,
      required this.montoAbonos,
      required this.contacto,
      required this.telContacto,
      required this.anuladoPor,
      required this.nombrePaciente,
      required this.nitFacturado,
      required this.nombreFacturado,
      required this.direccionFacturado,
      required this.dpi,
      required this.recibido,
      required this.noGuia,
      required this.notas,
      required this.idTranspote,
      required this.cantidadCuotas});
  factory Ventas.fromJson(Map<String, dynamic> json) {
    return Ventas(
        id: json['Id'],
        nFactura: json['NFactura'],
        tipo: json['Tipo'],
        fecha: json['Fecha'],
        vence: json['Vence'],
        codCLiente: json['CodCLiente'],
        nombreCliente: json['NombreCliente'],
        idUsuario: json['IdUsuario'],
        anulado: json['Anulado'],
        facturaCancelado: json['FacturaCancelado'],
        numApertura: json['NumApertura'],
        codMoneda: json['CodMoneda'],
        tipoCambio: json['TipoCambio'], // Aseguramos que sea double
        exonerar: json['Exonerar'],
        observaciones: json['Observaciones'],
        idVendedor: json['IdVendedor'],
        apertado: json['Apertado'],
        hora: json['Hora'],
        subTotal: json['SubTotal'],
        totalDescuento: json['TotalDescuento'],
        totalImpuesto: json['TotalImpuesto'],
        subTotalGravado: json['SubTotalGravado'],
        subTotalExento: json['SubTotalExento'],
        total: json['Total'],
        idBodega: json['IdBodega'],
        autorizacionFEL: json['AutorizacionFEL'],
        numeroFEL: json['NumeroFEL'],
        serieFEL: json['SerieFEL'],
        electronica: json['Electronica'],
        emisionFEL: json['EmisionFEL'],
        qr: json['QR'],
        totalLetras: json['TotalLetras'],
        noAbonos: json['NoAbonos'],
        montoAbonos: json['MontoAbonos'],
        contacto: json['Contacto'],
        telContacto: json['TelContacto'],
        anuladoPor: json['AnuladoPor'],
        nombrePaciente: json['NombrePaciente'],
        nitFacturado: json['NitFacturado'],
        nombreFacturado: json['NombreFacturado'],
        direccionFacturado: json['DireccionFacturado'],
        dpi: json['DPI'],
        recibido: json['Recibido'],
        noGuia: json['NoGuia'],
        notas: json['Notas'],
        idTranspote: json['IdTranspote'],
        cantidadCuotas: json['CantidadCuotas']);
  }

  Map<String, dynamic> toJson() {
    return {
      'Id': id,
      'NFactura': nFactura,
      'Tipo': tipo,
      'Fecha': fecha,
      'Vence': vence,
      'CodCLiente': codCLiente,
      'NombreCliente': nombreCliente,
      'IdUsuario': idUsuario,
      'Anulado': anulado,
      'FacturaCancelado': facturaCancelado,
      'NumApertura': numApertura,
      'CodMoneda': codMoneda,
      'TipoCambio': tipoCambio,
      'Exonerar': exonerar,
      'Observaciones': observaciones,
      'IdVendedor': idVendedor,
      'Apertado': apertado,
      'Hora': hora,
      'SubTotal': subTotal,
      'TotalDescuento': totalDescuento,
      'TotalImpuesto': totalImpuesto,
      'SubTotalGravado': subTotalGravado,
      'SubTotalExento': subTotalExento,
      'Total': total,
      'IdBodega': idBodega,
      'AutorizacionFEL': autorizacionFEL,
      'NumeroFEL': numeroFEL,
      'SerieFEL': serieFEL,
      'Electronica': electronica,
      'EmisionFEL': emisionFEL,
      'QR': qr,
      'TotalLetras': totalLetras,
      'NoAbonos': noAbonos,
      'MontoAbonos': montoAbonos,
      'Contacto': contacto,
      'TelContacto': telContacto,
      'AnuladoPor': anuladoPor,
      'NombrePaciente': nombrePaciente,
      'NITFacturado': nitFacturado,
      'NombreFacturado': nombreFacturado,
      'DireccionFacturado': direccionFacturado,
      'DPI': dpi,
      'Recibido': recibido,
      'NoGuia': noGuia,
      'Notas': notas,
      'IdTranspote': idTranspote,
      'CantidadCuotas': cantidadCuotas
    };
  }
}
